import os

ALPHA_API_KEY = os.environ.get("ALPHA_API_KEY", "6QDUB9YZIIJJABBX")

TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN", "YOUR_TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "YOUR_CHAT_ID")
